module.exports = {
  'z':  '808/808-Clap07.wav',
  'x':  '808/808-Cowbell2.wav',
  'c':  '808/hihat.wav',
  'v':  '808/808-Kicks33.wav',
  'a':  'cat/cat-meow6.wav',
  's':  '808/808-Snare25.wav',
  'd':  '808/808-Tom3.wav',
  'f':  'windows/Windows XP Balloon.wav',
  'q':  'windows/Windows XP Battery Critical.wav',
  'w':  'windows/Windows XP Battery Low.wav',
  'e': 'windows/Windows XP Critical Stop.wav',
  'r': 'windows/Windows XP Default.wav',
  'b': 'windows/Windows XP Ding.wav',
  'n': 'windows/Windows XP Error.wav',
  'm': 'windows/Windows XP Exclamation.wav',
  'g': 'windows/Windows XP Hardware Fail.wav',
  'h': 'windows/Windows XP Hardware Insert.wav',
  'j': 'windows/Windows XP Hardware Remove.wav',
  't': 'windows/Windows XP Information Bar.wav',
  'y': 'windows/Windows XP Logoff Sound.wav',
  'u': 'cat/cat-meow2.wav',
  '5': 'windows/Windows XP Menu Command.wav',
  '6': 'windows/Windows XP Notify.wav',
  '7': 'windows/Windows XP Print complete.wav',
  '1': 'windows/Windows XP Recycle.wav',
  '2': 'windows/Windows XP Ringin.wav',
  '3': 'windows/Windows XP Ringout.wav',
  '4': 'windows/Windows XP Shutdown.wav',
  '8': 'windows/Windows XP Start.wav',
  '9': 'windows/Windows XP Startup.wav',
  '0': 'windows/classic chimes.wav',
  'i': 'cat/cat-meow3.wav',
  'o': 'cat/cat-meow4.wav',
  '[': 'cat/cat-meow5.wav',
  'k': 'windows/classic recycle.wav',
  'l': 'windows/classic recycle.wav',
  'p': 'cat/cat-meow5.wav',
  'backtick': 'windows/windows xp pop-up blocked.wav',
  'comma':  '808/808-Clap07.wav',
  'period':  '808/808-Cowbell2.wav',
  'forwardslash':  '808/hihat.wav',
  'semicolon':  '808/808-Kicks33.wav',
  'quote':  '808/808-Kicks33.wav',
  'openbracket':  '808/808-Snare25.wav',
  'closebracket':  '808/808-Tom3.wav',
  'backslash':  '808/hihat.wav',
  'minus':  '808/808-Kicks33.wav'
 }
